/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.6.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QLabel *lblNameP_7;
    QPushButton *btnD10_P_5;
    QLineEdit *txtNdiceP_7;
    QLineEdit *txtNameP_5;
    QLineEdit *txtNdiceP_4;
    QPushButton *btnD12_P_2;
    QPushButton *btnD8_P_4;
    QPushButton *btnD20_P_4;
    QPushButton *btnD12_P_7;
    QLabel *lblNdiceP_2;
    QPushButton *btnD10_P_8;
    QLabel *lblNameP_6;
    QPushButton *btnD8_P_8;
    QPushButton *btnD8_P_1;
    QLabel *lblNameP_1;
    QLabel *lblPlayerN_6;
    QPushButton *btnD10_P_2;
    QPushButton *btnD6_P_3;
    QLabel *lblNdiceP_6;
    QPushButton *btnD8_P_7;
    QPushButton *btnD20_P_3;
    QPushButton *btnD4_P_5;
    QPushButton *btnD12_P_5;
    QPushButton *btnD6_P_6;
    QPushButton *btnD10_P_3;
    QPushButton *btnD6_P_5;
    QPushButton *btnD4_P_2;
    QLabel *lblNameP_3;
    QLabel *lblNdiceP_4;
    QLabel *lblPlayerN_2;
    QPushButton *btnD6_P_1;
    QLineEdit *txtNameP_3;
    QPushButton *btnD20_P_1;
    QLabel *lblNdiceP_1;
    QLineEdit *txtNameP_4;
    QPushButton *btnD6_P_8;
    QLineEdit *txtNameP_1;
    QLabel *lblNdiceP_7;
    QPushButton *btnD12_P_8;
    QLabel *lblNameP_2;
    QLabel *lblNameP_8;
    QPushButton *btnD6_P_7;
    QLabel *lblPlayerN_7;
    QPushButton *btnD8_P_3;
    QPushButton *btnD20_P_7;
    QPushButton *btnD4_P_8;
    QLabel *lblPlayerN_4;
    QPushButton *btnD6_P_4;
    QPushButton *btnD20_P_5;
    QLabel *lblNdiceP_3;
    QPushButton *btnD8_P_6;
    QPushButton *btnD4_P_4;
    QLabel *lblPlayerN_1;
    QLineEdit *txtNameP_8;
    QLabel *lblPlayerN_3;
    QPushButton *btnD12_P_4;
    QLabel *lblNameP_5;
    QLineEdit *txtNdiceP_1;
    QLineEdit *txtNdiceP_6;
    QLineEdit *txtNdiceP_8;
    QPushButton *btnD10_P_7;
    QPushButton *btnD20_P_6;
    QPushButton *btnD10_P_6;
    QLineEdit *txtNameP_6;
    QPushButton *btnD8_P_5;
    QPushButton *btnD20_P_8;
    QPushButton *btnD4_P_7;
    QPushButton *btnD12_P_1;
    QLabel *lblPlayerN_5;
    QPushButton *btnD4_P_1;
    QPushButton *btnD8_P_2;
    QLabel *lblPlayerN_8;
    QPushButton *btnD4_P_3;
    QLabel *lblNdiceP_5;
    QPushButton *btnD4_P_6;
    QPushButton *btnD10_P_1;
    QPushButton *btnD10_P_4;
    QPushButton *btnD6_P_2;
    QPushButton *btnD12_P_3;
    QLineEdit *txtNameP_7;
    QLineEdit *txtNdiceP_5;
    QLineEdit *txtNdiceP_2;
    QPushButton *btnD20_P_2;
    QLabel *lblNameP_4;
    QLineEdit *txtNdiceP_3;
    QLabel *lblNdiceP_8;
    QPushButton *btnD12_P_6;
    QLineEdit *txtNameP_2;
    QLineEdit *txtResult;
    QMenuBar *menubar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->resize(800, 621);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName("centralwidget");
        lblNameP_7 = new QLabel(centralwidget);
        lblNameP_7->setObjectName("lblNameP_7");
        lblNameP_7->setGeometry(QRect(420, 290, 49, 16));
        btnD10_P_5 = new QPushButton(centralwidget);
        btnD10_P_5->setObjectName("btnD10_P_5");
        btnD10_P_5->setGeometry(QRect(60, 450, 41, 41));
        txtNdiceP_7 = new QLineEdit(centralwidget);
        txtNdiceP_7->setObjectName("txtNdiceP_7");
        txtNdiceP_7->setGeometry(QRect(420, 370, 141, 24));
        txtNameP_5 = new QLineEdit(centralwidget);
        txtNameP_5->setObjectName("txtNameP_5");
        txtNameP_5->setGeometry(QRect(60, 310, 141, 24));
        txtNdiceP_4 = new QLineEdit(centralwidget);
        txtNdiceP_4->setObjectName("txtNdiceP_4");
        txtNdiceP_4->setGeometry(QRect(600, 120, 141, 24));
        btnD12_P_2 = new QPushButton(centralwidget);
        btnD12_P_2->setObjectName("btnD12_P_2");
        btnD12_P_2->setGeometry(QRect(290, 200, 41, 41));
        btnD8_P_4 = new QPushButton(centralwidget);
        btnD8_P_4->setObjectName("btnD8_P_4");
        btnD8_P_4->setGeometry(QRect(700, 150, 41, 41));
        btnD20_P_4 = new QPushButton(centralwidget);
        btnD20_P_4->setObjectName("btnD20_P_4");
        btnD20_P_4->setGeometry(QRect(700, 200, 41, 41));
        btnD12_P_7 = new QPushButton(centralwidget);
        btnD12_P_7->setObjectName("btnD12_P_7");
        btnD12_P_7->setGeometry(QRect(470, 450, 41, 41));
        lblNdiceP_2 = new QLabel(centralwidget);
        lblNdiceP_2->setObjectName("lblNdiceP_2");
        lblNdiceP_2->setGeometry(QRect(240, 100, 101, 16));
        btnD10_P_8 = new QPushButton(centralwidget);
        btnD10_P_8->setObjectName("btnD10_P_8");
        btnD10_P_8->setGeometry(QRect(600, 450, 41, 41));
        lblNameP_6 = new QLabel(centralwidget);
        lblNameP_6->setObjectName("lblNameP_6");
        lblNameP_6->setGeometry(QRect(240, 290, 49, 16));
        btnD8_P_8 = new QPushButton(centralwidget);
        btnD8_P_8->setObjectName("btnD8_P_8");
        btnD8_P_8->setGeometry(QRect(700, 400, 41, 41));
        btnD8_P_1 = new QPushButton(centralwidget);
        btnD8_P_1->setObjectName("btnD8_P_1");
        btnD8_P_1->setGeometry(QRect(160, 150, 41, 41));
        lblNameP_1 = new QLabel(centralwidget);
        lblNameP_1->setObjectName("lblNameP_1");
        lblNameP_1->setGeometry(QRect(60, 40, 49, 16));
        lblPlayerN_6 = new QLabel(centralwidget);
        lblPlayerN_6->setObjectName("lblPlayerN_6");
        lblPlayerN_6->setGeometry(QRect(450, 270, 81, 16));
        QFont font;
        font.setPointSize(12);
        font.setBold(true);
        lblPlayerN_6->setFont(font);
        lblPlayerN_6->setTextFormat(Qt::AutoText);
        btnD10_P_2 = new QPushButton(centralwidget);
        btnD10_P_2->setObjectName("btnD10_P_2");
        btnD10_P_2->setGeometry(QRect(240, 200, 41, 41));
        btnD6_P_3 = new QPushButton(centralwidget);
        btnD6_P_3->setObjectName("btnD6_P_3");
        btnD6_P_3->setGeometry(QRect(470, 150, 41, 41));
        lblNdiceP_6 = new QLabel(centralwidget);
        lblNdiceP_6->setObjectName("lblNdiceP_6");
        lblNdiceP_6->setGeometry(QRect(420, 350, 101, 16));
        btnD8_P_7 = new QPushButton(centralwidget);
        btnD8_P_7->setObjectName("btnD8_P_7");
        btnD8_P_7->setGeometry(QRect(520, 400, 41, 41));
        btnD20_P_3 = new QPushButton(centralwidget);
        btnD20_P_3->setObjectName("btnD20_P_3");
        btnD20_P_3->setGeometry(QRect(520, 200, 41, 41));
        btnD4_P_5 = new QPushButton(centralwidget);
        btnD4_P_5->setObjectName("btnD4_P_5");
        btnD4_P_5->setGeometry(QRect(60, 400, 41, 41));
        btnD12_P_5 = new QPushButton(centralwidget);
        btnD12_P_5->setObjectName("btnD12_P_5");
        btnD12_P_5->setGeometry(QRect(110, 450, 41, 41));
        btnD6_P_6 = new QPushButton(centralwidget);
        btnD6_P_6->setObjectName("btnD6_P_6");
        btnD6_P_6->setGeometry(QRect(290, 400, 41, 41));
        btnD10_P_3 = new QPushButton(centralwidget);
        btnD10_P_3->setObjectName("btnD10_P_3");
        btnD10_P_3->setGeometry(QRect(420, 200, 41, 41));
        btnD6_P_5 = new QPushButton(centralwidget);
        btnD6_P_5->setObjectName("btnD6_P_5");
        btnD6_P_5->setGeometry(QRect(110, 400, 41, 41));
        btnD4_P_2 = new QPushButton(centralwidget);
        btnD4_P_2->setObjectName("btnD4_P_2");
        btnD4_P_2->setGeometry(QRect(240, 150, 41, 41));
        lblNameP_3 = new QLabel(centralwidget);
        lblNameP_3->setObjectName("lblNameP_3");
        lblNameP_3->setGeometry(QRect(420, 40, 49, 16));
        lblNdiceP_4 = new QLabel(centralwidget);
        lblNdiceP_4->setObjectName("lblNdiceP_4");
        lblNdiceP_4->setGeometry(QRect(600, 100, 101, 16));
        lblPlayerN_2 = new QLabel(centralwidget);
        lblPlayerN_2->setObjectName("lblPlayerN_2");
        lblPlayerN_2->setGeometry(QRect(270, 20, 81, 16));
        lblPlayerN_2->setFont(font);
        lblPlayerN_2->setTextFormat(Qt::AutoText);
        btnD6_P_1 = new QPushButton(centralwidget);
        btnD6_P_1->setObjectName("btnD6_P_1");
        btnD6_P_1->setGeometry(QRect(110, 150, 41, 41));
        txtNameP_3 = new QLineEdit(centralwidget);
        txtNameP_3->setObjectName("txtNameP_3");
        txtNameP_3->setGeometry(QRect(420, 60, 141, 24));
        btnD20_P_1 = new QPushButton(centralwidget);
        btnD20_P_1->setObjectName("btnD20_P_1");
        btnD20_P_1->setGeometry(QRect(160, 200, 41, 41));
        lblNdiceP_1 = new QLabel(centralwidget);
        lblNdiceP_1->setObjectName("lblNdiceP_1");
        lblNdiceP_1->setGeometry(QRect(60, 100, 101, 16));
        txtNameP_4 = new QLineEdit(centralwidget);
        txtNameP_4->setObjectName("txtNameP_4");
        txtNameP_4->setGeometry(QRect(600, 60, 141, 24));
        btnD6_P_8 = new QPushButton(centralwidget);
        btnD6_P_8->setObjectName("btnD6_P_8");
        btnD6_P_8->setGeometry(QRect(650, 400, 41, 41));
        txtNameP_1 = new QLineEdit(centralwidget);
        txtNameP_1->setObjectName("txtNameP_1");
        txtNameP_1->setGeometry(QRect(60, 60, 141, 24));
        lblNdiceP_7 = new QLabel(centralwidget);
        lblNdiceP_7->setObjectName("lblNdiceP_7");
        lblNdiceP_7->setGeometry(QRect(60, 350, 101, 16));
        btnD12_P_8 = new QPushButton(centralwidget);
        btnD12_P_8->setObjectName("btnD12_P_8");
        btnD12_P_8->setGeometry(QRect(650, 450, 41, 41));
        lblNameP_2 = new QLabel(centralwidget);
        lblNameP_2->setObjectName("lblNameP_2");
        lblNameP_2->setGeometry(QRect(240, 40, 49, 16));
        lblNameP_8 = new QLabel(centralwidget);
        lblNameP_8->setObjectName("lblNameP_8");
        lblNameP_8->setGeometry(QRect(600, 290, 49, 16));
        btnD6_P_7 = new QPushButton(centralwidget);
        btnD6_P_7->setObjectName("btnD6_P_7");
        btnD6_P_7->setGeometry(QRect(470, 400, 41, 41));
        lblPlayerN_7 = new QLabel(centralwidget);
        lblPlayerN_7->setObjectName("lblPlayerN_7");
        lblPlayerN_7->setGeometry(QRect(90, 270, 81, 16));
        lblPlayerN_7->setFont(font);
        lblPlayerN_7->setTextFormat(Qt::AutoText);
        btnD8_P_3 = new QPushButton(centralwidget);
        btnD8_P_3->setObjectName("btnD8_P_3");
        btnD8_P_3->setGeometry(QRect(520, 150, 41, 41));
        btnD20_P_7 = new QPushButton(centralwidget);
        btnD20_P_7->setObjectName("btnD20_P_7");
        btnD20_P_7->setGeometry(QRect(520, 450, 41, 41));
        btnD4_P_8 = new QPushButton(centralwidget);
        btnD4_P_8->setObjectName("btnD4_P_8");
        btnD4_P_8->setGeometry(QRect(600, 400, 41, 41));
        lblPlayerN_4 = new QLabel(centralwidget);
        lblPlayerN_4->setObjectName("lblPlayerN_4");
        lblPlayerN_4->setGeometry(QRect(450, 20, 81, 16));
        lblPlayerN_4->setFont(font);
        lblPlayerN_4->setTextFormat(Qt::AutoText);
        btnD6_P_4 = new QPushButton(centralwidget);
        btnD6_P_4->setObjectName("btnD6_P_4");
        btnD6_P_4->setGeometry(QRect(650, 150, 41, 41));
        btnD20_P_5 = new QPushButton(centralwidget);
        btnD20_P_5->setObjectName("btnD20_P_5");
        btnD20_P_5->setGeometry(QRect(160, 450, 41, 41));
        lblNdiceP_3 = new QLabel(centralwidget);
        lblNdiceP_3->setObjectName("lblNdiceP_3");
        lblNdiceP_3->setGeometry(QRect(420, 100, 101, 16));
        btnD8_P_6 = new QPushButton(centralwidget);
        btnD8_P_6->setObjectName("btnD8_P_6");
        btnD8_P_6->setGeometry(QRect(340, 400, 41, 41));
        btnD4_P_4 = new QPushButton(centralwidget);
        btnD4_P_4->setObjectName("btnD4_P_4");
        btnD4_P_4->setGeometry(QRect(600, 150, 41, 41));
        lblPlayerN_1 = new QLabel(centralwidget);
        lblPlayerN_1->setObjectName("lblPlayerN_1");
        lblPlayerN_1->setGeometry(QRect(90, 20, 81, 16));
        lblPlayerN_1->setFont(font);
        lblPlayerN_1->setTextFormat(Qt::AutoText);
        txtNameP_8 = new QLineEdit(centralwidget);
        txtNameP_8->setObjectName("txtNameP_8");
        txtNameP_8->setGeometry(QRect(600, 310, 141, 24));
        lblPlayerN_3 = new QLabel(centralwidget);
        lblPlayerN_3->setObjectName("lblPlayerN_3");
        lblPlayerN_3->setGeometry(QRect(630, 20, 81, 16));
        lblPlayerN_3->setFont(font);
        lblPlayerN_3->setTextFormat(Qt::AutoText);
        btnD12_P_4 = new QPushButton(centralwidget);
        btnD12_P_4->setObjectName("btnD12_P_4");
        btnD12_P_4->setGeometry(QRect(650, 200, 41, 41));
        lblNameP_5 = new QLabel(centralwidget);
        lblNameP_5->setObjectName("lblNameP_5");
        lblNameP_5->setGeometry(QRect(60, 290, 49, 16));
        txtNdiceP_1 = new QLineEdit(centralwidget);
        txtNdiceP_1->setObjectName("txtNdiceP_1");
        txtNdiceP_1->setGeometry(QRect(60, 120, 141, 24));
        txtNdiceP_6 = new QLineEdit(centralwidget);
        txtNdiceP_6->setObjectName("txtNdiceP_6");
        txtNdiceP_6->setGeometry(QRect(240, 370, 141, 24));
        txtNdiceP_8 = new QLineEdit(centralwidget);
        txtNdiceP_8->setObjectName("txtNdiceP_8");
        txtNdiceP_8->setGeometry(QRect(600, 370, 141, 24));
        btnD10_P_7 = new QPushButton(centralwidget);
        btnD10_P_7->setObjectName("btnD10_P_7");
        btnD10_P_7->setGeometry(QRect(420, 450, 41, 41));
        btnD20_P_6 = new QPushButton(centralwidget);
        btnD20_P_6->setObjectName("btnD20_P_6");
        btnD20_P_6->setGeometry(QRect(340, 450, 41, 41));
        btnD10_P_6 = new QPushButton(centralwidget);
        btnD10_P_6->setObjectName("btnD10_P_6");
        btnD10_P_6->setGeometry(QRect(240, 450, 41, 41));
        txtNameP_6 = new QLineEdit(centralwidget);
        txtNameP_6->setObjectName("txtNameP_6");
        txtNameP_6->setGeometry(QRect(240, 310, 141, 24));
        btnD8_P_5 = new QPushButton(centralwidget);
        btnD8_P_5->setObjectName("btnD8_P_5");
        btnD8_P_5->setGeometry(QRect(160, 400, 41, 41));
        btnD20_P_8 = new QPushButton(centralwidget);
        btnD20_P_8->setObjectName("btnD20_P_8");
        btnD20_P_8->setGeometry(QRect(700, 450, 41, 41));
        btnD4_P_7 = new QPushButton(centralwidget);
        btnD4_P_7->setObjectName("btnD4_P_7");
        btnD4_P_7->setGeometry(QRect(420, 400, 41, 41));
        btnD12_P_1 = new QPushButton(centralwidget);
        btnD12_P_1->setObjectName("btnD12_P_1");
        btnD12_P_1->setGeometry(QRect(110, 200, 41, 41));
        lblPlayerN_5 = new QLabel(centralwidget);
        lblPlayerN_5->setObjectName("lblPlayerN_5");
        lblPlayerN_5->setGeometry(QRect(270, 270, 81, 16));
        lblPlayerN_5->setFont(font);
        lblPlayerN_5->setTextFormat(Qt::AutoText);
        btnD4_P_1 = new QPushButton(centralwidget);
        btnD4_P_1->setObjectName("btnD4_P_1");
        btnD4_P_1->setGeometry(QRect(60, 150, 41, 41));
        btnD8_P_2 = new QPushButton(centralwidget);
        btnD8_P_2->setObjectName("btnD8_P_2");
        btnD8_P_2->setGeometry(QRect(340, 150, 41, 41));
        lblPlayerN_8 = new QLabel(centralwidget);
        lblPlayerN_8->setObjectName("lblPlayerN_8");
        lblPlayerN_8->setGeometry(QRect(630, 270, 81, 16));
        lblPlayerN_8->setFont(font);
        lblPlayerN_8->setTextFormat(Qt::AutoText);
        btnD4_P_3 = new QPushButton(centralwidget);
        btnD4_P_3->setObjectName("btnD4_P_3");
        btnD4_P_3->setGeometry(QRect(420, 150, 41, 41));
        lblNdiceP_5 = new QLabel(centralwidget);
        lblNdiceP_5->setObjectName("lblNdiceP_5");
        lblNdiceP_5->setGeometry(QRect(600, 350, 101, 16));
        btnD4_P_6 = new QPushButton(centralwidget);
        btnD4_P_6->setObjectName("btnD4_P_6");
        btnD4_P_6->setGeometry(QRect(240, 400, 41, 41));
        btnD10_P_1 = new QPushButton(centralwidget);
        btnD10_P_1->setObjectName("btnD10_P_1");
        btnD10_P_1->setGeometry(QRect(60, 200, 41, 41));
        btnD10_P_4 = new QPushButton(centralwidget);
        btnD10_P_4->setObjectName("btnD10_P_4");
        btnD10_P_4->setGeometry(QRect(600, 200, 41, 41));
        btnD6_P_2 = new QPushButton(centralwidget);
        btnD6_P_2->setObjectName("btnD6_P_2");
        btnD6_P_2->setGeometry(QRect(290, 150, 41, 41));
        btnD12_P_3 = new QPushButton(centralwidget);
        btnD12_P_3->setObjectName("btnD12_P_3");
        btnD12_P_3->setGeometry(QRect(470, 200, 41, 41));
        txtNameP_7 = new QLineEdit(centralwidget);
        txtNameP_7->setObjectName("txtNameP_7");
        txtNameP_7->setGeometry(QRect(420, 310, 141, 24));
        txtNdiceP_5 = new QLineEdit(centralwidget);
        txtNdiceP_5->setObjectName("txtNdiceP_5");
        txtNdiceP_5->setGeometry(QRect(60, 370, 141, 24));
        txtNdiceP_2 = new QLineEdit(centralwidget);
        txtNdiceP_2->setObjectName("txtNdiceP_2");
        txtNdiceP_2->setGeometry(QRect(240, 120, 141, 24));
        btnD20_P_2 = new QPushButton(centralwidget);
        btnD20_P_2->setObjectName("btnD20_P_2");
        btnD20_P_2->setGeometry(QRect(340, 200, 41, 41));
        lblNameP_4 = new QLabel(centralwidget);
        lblNameP_4->setObjectName("lblNameP_4");
        lblNameP_4->setGeometry(QRect(600, 40, 49, 16));
        txtNdiceP_3 = new QLineEdit(centralwidget);
        txtNdiceP_3->setObjectName("txtNdiceP_3");
        txtNdiceP_3->setGeometry(QRect(420, 120, 141, 24));
        lblNdiceP_8 = new QLabel(centralwidget);
        lblNdiceP_8->setObjectName("lblNdiceP_8");
        lblNdiceP_8->setGeometry(QRect(240, 350, 101, 16));
        btnD12_P_6 = new QPushButton(centralwidget);
        btnD12_P_6->setObjectName("btnD12_P_6");
        btnD12_P_6->setGeometry(QRect(290, 450, 41, 41));
        txtNameP_2 = new QLineEdit(centralwidget);
        txtNameP_2->setObjectName("txtNameP_2");
        txtNameP_2->setGeometry(QRect(240, 60, 141, 24));
        txtResult = new QLineEdit(centralwidget);
        txtResult->setObjectName("txtResult");
        txtResult->setGeometry(QRect(200, 510, 401, 71));
        QPalette palette;
        QBrush brush(QColor(170, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        txtResult->setPalette(palette);
        QFont font1;
        font1.setPointSize(16);
        font1.setBold(true);
        txtResult->setFont(font1);
        txtResult->setAlignment(Qt::AlignCenter);
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName("menubar");
        menubar->setGeometry(QRect(0, 0, 800, 21));
        MainWindow->setMenuBar(menubar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        lblNameP_7->setText(QCoreApplication::translate("MainWindow", "Name :", nullptr));
        btnD10_P_5->setText(QCoreApplication::translate("MainWindow", "D10", nullptr));
        btnD12_P_2->setText(QCoreApplication::translate("MainWindow", "D12", nullptr));
        btnD8_P_4->setText(QCoreApplication::translate("MainWindow", "D8", nullptr));
        btnD20_P_4->setText(QCoreApplication::translate("MainWindow", "D20", nullptr));
        btnD12_P_7->setText(QCoreApplication::translate("MainWindow", "D12", nullptr));
        lblNdiceP_2->setText(QCoreApplication::translate("MainWindow", "# of dice to trow :", nullptr));
        btnD10_P_8->setText(QCoreApplication::translate("MainWindow", "D10", nullptr));
        lblNameP_6->setText(QCoreApplication::translate("MainWindow", "Name :", nullptr));
        btnD8_P_8->setText(QCoreApplication::translate("MainWindow", "D8", nullptr));
        btnD8_P_1->setText(QCoreApplication::translate("MainWindow", "D8", nullptr));
        lblNameP_1->setText(QCoreApplication::translate("MainWindow", "Name :", nullptr));
        lblPlayerN_6->setText(QCoreApplication::translate("MainWindow", "PLAYER 7", nullptr));
        btnD10_P_2->setText(QCoreApplication::translate("MainWindow", "D10", nullptr));
        btnD6_P_3->setText(QCoreApplication::translate("MainWindow", "D6", nullptr));
        lblNdiceP_6->setText(QCoreApplication::translate("MainWindow", "# of dice to trow :", nullptr));
        btnD8_P_7->setText(QCoreApplication::translate("MainWindow", "D8", nullptr));
        btnD20_P_3->setText(QCoreApplication::translate("MainWindow", "D20", nullptr));
        btnD4_P_5->setText(QCoreApplication::translate("MainWindow", "D4", nullptr));
        btnD12_P_5->setText(QCoreApplication::translate("MainWindow", "D12", nullptr));
        btnD6_P_6->setText(QCoreApplication::translate("MainWindow", "D6", nullptr));
        btnD10_P_3->setText(QCoreApplication::translate("MainWindow", "D10", nullptr));
        btnD6_P_5->setText(QCoreApplication::translate("MainWindow", "D6", nullptr));
        btnD4_P_2->setText(QCoreApplication::translate("MainWindow", "D4", nullptr));
        lblNameP_3->setText(QCoreApplication::translate("MainWindow", "Name :", nullptr));
        lblNdiceP_4->setText(QCoreApplication::translate("MainWindow", "# of dice to trow :", nullptr));
        lblPlayerN_2->setText(QCoreApplication::translate("MainWindow", "PLAYER 2", nullptr));
        btnD6_P_1->setText(QCoreApplication::translate("MainWindow", "D6", nullptr));
        btnD20_P_1->setText(QCoreApplication::translate("MainWindow", "D20", nullptr));
        lblNdiceP_1->setText(QCoreApplication::translate("MainWindow", "# of dice to trow :", nullptr));
        btnD6_P_8->setText(QCoreApplication::translate("MainWindow", "D6", nullptr));
        lblNdiceP_7->setText(QCoreApplication::translate("MainWindow", "# of dice to trow :", nullptr));
        btnD12_P_8->setText(QCoreApplication::translate("MainWindow", "D12", nullptr));
        lblNameP_2->setText(QCoreApplication::translate("MainWindow", "Name :", nullptr));
        lblNameP_8->setText(QCoreApplication::translate("MainWindow", "Name :", nullptr));
        btnD6_P_7->setText(QCoreApplication::translate("MainWindow", "D6", nullptr));
        lblPlayerN_7->setText(QCoreApplication::translate("MainWindow", "PLAYER 5", nullptr));
        btnD8_P_3->setText(QCoreApplication::translate("MainWindow", "D8", nullptr));
        btnD20_P_7->setText(QCoreApplication::translate("MainWindow", "D20", nullptr));
        btnD4_P_8->setText(QCoreApplication::translate("MainWindow", "D4", nullptr));
        lblPlayerN_4->setText(QCoreApplication::translate("MainWindow", "PLAYER 3", nullptr));
        btnD6_P_4->setText(QCoreApplication::translate("MainWindow", "D6", nullptr));
        btnD20_P_5->setText(QCoreApplication::translate("MainWindow", "D20", nullptr));
        lblNdiceP_3->setText(QCoreApplication::translate("MainWindow", "# of dice to trow :", nullptr));
        btnD8_P_6->setText(QCoreApplication::translate("MainWindow", "D8", nullptr));
        btnD4_P_4->setText(QCoreApplication::translate("MainWindow", "D4", nullptr));
        lblPlayerN_1->setText(QCoreApplication::translate("MainWindow", "PLAYER 1", nullptr));
        lblPlayerN_3->setText(QCoreApplication::translate("MainWindow", "PLAYER 4", nullptr));
        btnD12_P_4->setText(QCoreApplication::translate("MainWindow", "D12", nullptr));
        lblNameP_5->setText(QCoreApplication::translate("MainWindow", "Name :", nullptr));
        btnD10_P_7->setText(QCoreApplication::translate("MainWindow", "D10", nullptr));
        btnD20_P_6->setText(QCoreApplication::translate("MainWindow", "D20", nullptr));
        btnD10_P_6->setText(QCoreApplication::translate("MainWindow", "D10", nullptr));
        btnD8_P_5->setText(QCoreApplication::translate("MainWindow", "D8", nullptr));
        btnD20_P_8->setText(QCoreApplication::translate("MainWindow", "D20", nullptr));
        btnD4_P_7->setText(QCoreApplication::translate("MainWindow", "D4", nullptr));
        btnD12_P_1->setText(QCoreApplication::translate("MainWindow", "D12", nullptr));
        lblPlayerN_5->setText(QCoreApplication::translate("MainWindow", "PLAYER 6", nullptr));
        btnD4_P_1->setText(QCoreApplication::translate("MainWindow", "D4", nullptr));
        btnD8_P_2->setText(QCoreApplication::translate("MainWindow", "D8", nullptr));
        lblPlayerN_8->setText(QCoreApplication::translate("MainWindow", "PLAYER 8", nullptr));
        btnD4_P_3->setText(QCoreApplication::translate("MainWindow", "D4", nullptr));
        lblNdiceP_5->setText(QCoreApplication::translate("MainWindow", "# of dice to trow :", nullptr));
        btnD4_P_6->setText(QCoreApplication::translate("MainWindow", "D4", nullptr));
        btnD10_P_1->setText(QCoreApplication::translate("MainWindow", "D10", nullptr));
        btnD10_P_4->setText(QCoreApplication::translate("MainWindow", "D10", nullptr));
        btnD6_P_2->setText(QCoreApplication::translate("MainWindow", "D6", nullptr));
        btnD12_P_3->setText(QCoreApplication::translate("MainWindow", "D12", nullptr));
        btnD20_P_2->setText(QCoreApplication::translate("MainWindow", "D20", nullptr));
        lblNameP_4->setText(QCoreApplication::translate("MainWindow", "Name :", nullptr));
        lblNdiceP_8->setText(QCoreApplication::translate("MainWindow", "# of dice to trow :", nullptr));
        btnD12_P_6->setText(QCoreApplication::translate("MainWindow", "D12", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
